### ISSUE TITLE
conda search -o results in malformed version string

### ISSUE THREAD

**Issue by jwkvam** [conda-forge/aubio-feedstock#7]
I don't know if the error is with conda or this package but I get the following error running this command.

```
$ conda search -o
Fetching package metadata .............

The following stack trace is in reference to package:

	conda-forge::aubio-0.4.5~git+67a3053-np111py35_0.tar.bz2

CondaValueError: Value error: Malformed version string '0.4.5~git+67a3053': invalid character(s).
```

**Comment by piem** [comment]
it was an error on my side, as I wrongly assumed branches would not be uploaded (i know, i should rtfm). :-\

that said, the upload script succeeded on osx, although i guess it should fail uploading packages build with an invalid version number.

@conda-forge/core could these package be manually removed?

thanks, piem

**Comment by piem** [comment]
@conda-forge/core any news on this? we don't want to break conda-forge on osx :-\

**Comment by ocefpaf** [comment]
> @conda-forge/core could these package be manually removed?

Looking into it....

**Comment by ocefpaf** [comment]
@piem let me know if I got all: https://anaconda.org/conda-forge/aubio/files?page=1

**Comment by piem** [comment]
@ocefpaf yes, looking much better, thank you !
